export const ROUTES = {
  HOME: "/",
  REGISTRATION: "/registration",
  ABOUT: "/about",
  //   CONTACT: "/contact",
  ACCOUNT: "/account",
  PRODUCTS: "/products",
  USERS: "/users",
  // USER: "/users/:userId",
  DELETE_USER: "",
  LOGIN: "/login",
  LOGOUT: "/logout",
  ADD_PRODUCT: "/add-product",
  DELETE_PRODUCT: "",
  ADMIN: "/admin",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_USERS: "/admin/users",
  CART: "/cart",
  CHECKOUT: "/checkout",
  TEAM: "/team",
  CAREERS: "/careers",
  FAQ: "/faq",
  HELPCENTER: "/helpcenter",
  CONTACTS: "/contacts",
  NOT_AUTH: "/notauthorized",
} as const;
